### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by wytrych** [incuna/angular-input-fields#1]
@maxpeterson @grahamgilchrist @henrahmagix @Minglee01 Please take a look at this new repo. Any suggestions welcome.

**Comment by Minglee01** [comment]
It looks ok. But maybe split the directives into seperate files.

On 25 August 2015 at 09:52, Marcin Wolniewicz <notifications@github.com>
wrote:

> @maxpeterson <https://github.com/maxpeterson> @grahamgilchrist
> <https://github.com/grahamgilchrist> @henrahmagix
> <https://github.com/henrahmagix> @Minglee01 <https://github.com/Minglee01>
> Please take a look at this new repo. Any suggestions welcome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/incuna/angular-input-fields/issues/1>.
>



-- 

Ming Lee - Junior Frontend ProgrammerMing@incuna.com
01865 791 494
Incuna Ltd, 16 Middle Way, Oxford, OX2 7LH

**Comment by henrahmagix** [comment]
Do all the templates need the `-input` suffix?

**Comment by henrahmagix** [comment]
`switch-input` has a dependency on angular-bootstrap: see `btn-radio` directive used here https://github.com/incuna/angular-input-fields/blob/59a875a8a30332a65fce9a201c289fb227f0cbb6/src/templates/type/switch-input.html#L3

**Comment by grahamgilchrist** [comment]
Yeah, would good to seperate each directive to it's own file to help readability, merging, choice of import etc.

**Comment by grahamgilchrist** [comment]
Moved issue to split modules in #12, so closing this issue

**Comment by grahamgilchrist** [comment]
Issue to add bower bootstrap dependency added in #11
